package com.example.blood_donor.ui.utils

object LocalizedStrings {
    private val en = mapOf(
        "settings" to "Settings",
        "account" to "Account",
        "edit_profile" to "Edit Profile",
        "change_password" to "Change Password",
        "push_notifications" to "Push Notifications",
        "sos_alerts" to "SOS Alerts",
        "privacy_policy" to "Privacy Policy",
        "about" to "About Smart Blood Finder",
        "logout" to "Logout",
        "select_language" to "Preferred Language",
        "english" to "English (English)",
        "tamil" to "Tamil (தமிழ்)",
        "hindi" to "Hindi (हिन्दी)",
        "save_changes" to "Save Changes",
        "welcome" to "Welcome Back",
        "sign_in_save_lives" to "Sign in to save lives",
        "email_or_phone" to "Email or Phone Number",
        "password" to "Password",
        "login" to "Login",
        "language" to "Language",
        "change_language_desc" to "Choose your default application language",
        "theme" to "Theme Settings",
        "edit_profile_desc" to "Update your name, age, blood group",
        "change_password_desc" to "Keep your account secure",
        "notifications_desc" to "Get notified about blood requests",
        "sos_desc" to "Receive emergency blood alerts nearby",
        "privacy_desc" to "How we handle your data",
        "about_desc" to "Version 1.0.0",
        
        "home" to "Home",
        "map" to "Map",
        "chat" to "Chat",
        "alerts" to "Alerts",
        "profile" to "Profile",
        
        "hospital_dashboard" to "Hospital Dashboard",
        "donor_dashboard" to "Donor Dashboard",
        "patient_dashboard" to "Patient Dashboard",
        "good_morning" to "Good morning 👋",
        "blood_group" to "Blood Group",
        "age" to "Age",
        "gender" to "Gender",
        "last_donated" to "Last Donated",
        "next_eligible" to "Next Eligible",
        "phone" to "Phone",
        "email" to "Email",
        
        "emergency_sos" to "Emergency SOS",
        "request_blood" to "Request Blood",
        "blood_group_needed" to "Blood Group Needed",
        "hospital_name" to "Hospital Name",
        "units_required" to "Units Required",
        "urgency" to "Urgency",
        "submit_request" to "Submit Request",
        "create_blood_request" to "Create Blood Request",
        "hospital_name_location" to "Hospital Name / Location",
        "units_pints" to "Units (Pints)",
        "urgency_level" to "Urgency (Low/High/Critical)",
        "broadcast_request" to "Broadcast Request to Donors",
        
        "ai_donor_matching" to " Donor Matching",
        "scanning_donors" to " is scanning %d donors",
        "all_donors" to "All Donors",
        "available" to "Available",
        "busy" to "Busy",
        "within_5km" to "Within 5km",
        "exact_match" to "Exact",
        "compatible_match" to "Compatible",
        "call_donor" to "Call",
        "chat_donor" to "Chat",
        
        "remember_me" to "Remember me",
        "error_invalid_credentials" to "Incorrect phone number or password. Please check your credentials and try again.",
        "error_network_unavailable" to "Network unavailable. Please check your connection.",
        "error_server_error" to "Server error. Please try again later.",
        "error_not_found" to "Server endpoint not found. Please contact support.",
        "error_invalid_password" to "Incorrect password. Please check your password and try again.",
        "error_not_registered" to "This phone number or email is not registered.",
        "please_fill_all_fields_pwd" to "Please fill all fields. Password must be at least 6 characters.",
        "please_enter_age_gender" to "Please enter your age and gender.",
        "you_are_here" to "You are here",
        "please_enter_phone" to "Please enter phone number",
        "reset_otp_sent" to "Reset OTP sent: 654321",
        "please_fill_all_fields" to "Please fill all fields",
        "password_reset_success" to "Password reset successful! Please login.",
        
        "recent_alerts" to "Notifications",
        "no_recent_alerts" to "No recent alerts",
        "create_account" to "Create Account",
        "new_here" to "New here? ",
        "register" to "Register",
        "full_name" to "Full Name",
        "confirm_password" to "Confirm Password",
        "user_type" to "User Type",
        "donor" to "Donor",
        "patient" to "Patient",
        "hospital" to "Hospital",
        "license_number" to "License Number",
        "already_member" to "Already a member? ",
        "otp_title" to "OTP Verification",
        "otp_desc" to "Enter the 6-digit OTP code sent to your phone.",
        "verify" to "Verify",
        "resend_otp" to "Resend OTP",
        
        "location" to "Location",
        "update_location" to "Update Location",
        "select_state" to "Select State",
        "select_district" to "Select District",
        "enter_city" to "Enter City",
        "save" to "Save",
        "cancel" to "Cancel",
        "accept" to "Accept",
        "decline" to "Decline",
        "today_status" to "Today's Status",
        "available_hours" to "Available Hours",
        "morning" to "Morning",
        "afternoon" to "Afternoon",
        "evening" to "Evening",
        "sos_broadcast_success" to "Emergency SOS broadcasted successfully in-app!",
        "sos_request_desc" to "Need blood? Tap to alert matched donors",
        "best_match" to "Best Match For You",
        "see_all" to "See all >",
        "contact_donor" to "Contact Donor",
        "other_compatible" to "Other Compatible Donors",
        "view_all" to "View all >",
        "no_donors_found" to "No other nearby donors found",
        "update_avail_today" to "Update availability today?",
        "let_patients_know" to "Let patients know if you're ready to donate.",
        "update" to "Update",
        "donor_summary" to "Your Donor Summary",
        "donor_registered" to "❤️ You are registered as a blood donor!",
        "donor_registered_desc" to "When patients near you need your blood type, they will be able to see your profile and contact you.",
        "available_now" to "Available Now",
        "day_lock_rule" to "90-Day Lock Rule",
        "alerts_active" to "Alerts Active",
        "ai_tip_of_day" to " Tip of the Day",
        "error_already_registered" to "This phone number is already registered. Please login.",
        "save_login_title" to "Save login information?",
        "save_login_desc" to "Save your credentials for faster login next time.",
        "not_now" to "Not now",
        "onboarding_title_1" to " Donor Matching",
        "onboarding_desc_1" to "Our  finds the most compatible blood donor nearby in seconds — matched by blood group, health score, and distance.",
        "onboarding_title_2" to "Emergency SOS Alerts",
        "onboarding_desc_2" to "Send SOS alerts simultaneously via App notifications and SMS. Works even without internet.",
        "onboarding_title_3" to "Live Donor Tracking",
        "onboarding_desc_3" to "See a live map of available donors near you, complete with status and real-time updates.",
        "skip" to "Skip",
        "get_started" to "Get Started",
        "forgot_password" to "Forgot password?",
        "please_enter_phone_password" to "Please enter your phone number and password",
        "reset_password_title" to "Reset Password",
        "forgot_password_desc" to "Enter your phone number to receive a simulated reset OTP (654321).",
        "phone_number_placeholder" to "Phone Number",
        "send_otp" to "Send OTP",
        "cancel" to "Cancel",
        "enter_new_password_title" to "Enter New Password",
        "enter_new_password_desc" to "Enter the OTP code sent to your phone and choose a new password.",
        "otp_code_placeholder" to "OTP Code (e.g. 654321)",
        "new_password_placeholder" to "New Password",
        "create_account_title" to "Create Account",
        "i_am_a" to "I am a...",
        "choose_role_desc" to "Choose your role to get started",
        "blood_donor_role" to "Blood Donor",
        "blood_donor_role_desc" to "Register as a donor and help save lives.",
        "patient_family_role" to "Patient / Family",
        "patient_family_role_desc" to "Request blood urgently.",
        "hospital_role" to "Hospital",
        "hospital_role_desc" to "Manage blood requests.",
        "basic_info_title" to "Basic Info",
        "institution_name_label" to "Institution Name",
        "patient_family_name_label" to "Patient / Family Name",
        "full_name_label" to "Full Name",
        "email_address_label" to "Email Address",
        "continue_button" to "Continue",
        "patient_details_title" to "Patient Details",
        "donor_details_title" to "Donor Details",
        "last_donation_date_label" to "Last Donation Date (YYYY-MM-DD) [Optional]",
        "save_button" to "Save",
        "verify_phone_title" to "Verify Phone",
        "enter_otp_code_title" to "Enter OTP Code",
        "otp_sent_desc" to "We have sent a verification code to %s.\nPlease enter the code below to activate your account.",
        "enter_6digit_placeholder" to "Enter 6-digit code",
        "simulated_otp_banner" to "Simulated OTP code is 123456",
        "verify_activate_button" to "Verify & Activate",
        "please_enter_valid_otp" to "Please enter a valid 6-digit code",
        "compatible_percent" to "%s%% compatible",
        "km_away" to "%s km away",
        "messages_title" to "Messages",
        "no_recent_conversations" to "No recent conversations",
        "notifications_title" to "Notifications",
        "mark_all_read" to "Mark all read",
        "no_recent_alerts" to "No recent alerts.",
        "alert_needed_template" to "%s: %d unit(s) of %s needed at %s",
        "my_profile_title" to "My Profile",
        "complete_profile_title" to "Complete Your Profile",
        "complete_profile_desc" to "Please enter your blood group and details to continue.",
        "save_continue_button" to "Save & Continue",
        "ready_to_donate" to "Ready to donate now",
        "currently_unavailable" to "Currently unavailable",
        "not_available_to_donate" to "Not available to donate",
        "morning_hours" to "6:00 AM - 12:00 PM",
        "afternoon_hours" to "12:00 PM - 6:00 PM",
        "evening_hours" to "6:00 PM - 10:00 PM",
        "updated_just_now" to "Updated just now",
        "updated_minutes_ago" to "Updated %d min ago",
        "preferences_header" to "Preferences",
        "server_url_label" to "Server URL",
        "server_url_desc" to "Configure backend connection",
        "server_config_title" to "Server Configuration",
        "enter_server_url_desc" to "Enter the backend API server URL:",
        "ok_button" to "OK",
        "critical_sos_alerts_channel" to "Critical SOS Alerts",
        "critical_sos_desc" to "Immediate life-saving blood requirements",
        "standard_sos_alerts_channel" to "Standard SOS Alerts",
        "standard_sos_desc" to "General blood requirements",
        "urgent_blood_needed" to "🚨 URGENT: %s Needed!",
        "blood_request_title" to "Blood Request: %s",
        "units_needed_at_hospital" to "%d unit(s) needed at %s."
    )

    private val ta = mapOf(
        "settings" to "அமைப்புகள்",
        "account" to "கணக்கு",
        "edit_profile" to "சுயவிவரத்தை திருத்து",
        "change_password" to "கடவுச்சொல்லை மாற்று",
        "push_notifications" to "அறிவிப்புகள்",
        "sos_alerts" to "அவசரகால எச்சரிக்கைகள்",
        "privacy_policy" to "தனியுரிமைக் கொள்கை",
        "about" to "ஸ்மார்ட் பிளட் ஃபைண்டர் பற்றி",
        "logout" to "வெளியேறு",
        "select_language" to "விருப்பமான மொழி",
        "english" to "ஆங்கிலம் (English)",
        "tamil" to "தமிழ் (தமிழ்)",
        "hindi" to "இந்தி (हिन्दी)",
        "save_changes" to "மாற்றங்களைச் சேமி",
        "welcome" to "மீண்டும் வருக",
        "sign_in_save_lives" to "உயிரைக் காப்பாற்ற உள்நுழையவும்",
        "email_or_phone" to "மின்னஞ்சல் அல்லது தொலைபேசி எண்",
        "password" to "கடவுச்சொல்",
        "login" to "உள்நுழைக",
        "language" to "மொழி",
        "change_language_desc" to "விண்ணப்பத்தின் இயல்புநிலை மொழியைத் தேர்ந்தெடுக்கவும்",
        "theme" to "கருப்பொருள் அமைப்புகள்",
        "edit_profile_desc" to "உங்கள் பெயர், வயது, இரத்தக் குழுவை மாற்றவும்",
        "change_password_desc" to "உங்கள் கணக்கை பாதுகாப்பாக வைத்திருங்கள்",
        "notifications_desc" to "இரத்தக் கோரிக்கைகள் குறித்து அறிவிப்பைப் பெறுங்கள்",
        "sos_desc" to "அருகிலுள்ள அவசர இரத்த எச்சரிக்கைகளைப் பெறுங்கள்",
        "privacy_desc" to "உங்கள் தரவை நாங்கள் எவ்வாறு கையாளுகிறோம்",
        "about_desc" to "பதிப்பு 1.0.0",
        
        "home" to "முகப்பு",
        "map" to "வரைபடம்",
        "chat" to "அரட்டை",
        "alerts" to "அறிவிப்புகள்",
        "profile" to "சுயவிவரம்",
        
        "hospital_dashboard" to "மருத்துவமனை டாஷ்போர்டு",
        "donor_dashboard" to "கொடையாளர் டாஷ்போர்டு",
        "patient_dashboard" to "நோயாளி டாஷ்போர்டு",
        "good_morning" to "காலை வணக்கம் 👋",
        "blood_group" to "இரத்தக் குழு",
        "age" to "வயது",
        "gender" to "பாலினம்",
        "last_donated" to "கடைசியாக தானம் செய்தது",
        "next_eligible" to "அடுத்த தகுதி",
        "phone" to "தொலைபேசி",
        "email" to "மின்னஞ்சல்",
        
        "emergency_sos" to "அவசரகால SOS",
        "request_blood" to "இரத்தம் தேவை",
        "blood_group_needed" to "தேவைப்படும் இரத்த வகை",
        "hospital_name" to "மருத்துவமனை பெயர்",
        "units_required" to "தேவைப்படும் அலகுகள்",
        "urgency" to "அவசரம்",
        "submit_request" to "கோரிக்கையைச் சமர்ப்பிக்கவும்",
        "create_blood_request" to "இரத்தக் கோரிக்கையை உருவாக்கு",
        "hospital_name_location" to "மருத்துவமனை பெயர் / இடம்",
        "units_pints" to "அலகுகள் (பைண்டுகள்)",
        "urgency_level" to "அவசியத்தன்மை (குறைந்த/அதிக/மிகவும் அவசரம்)",
        "broadcast_request" to "கொடையாளர்களுக்கு கோரிக்கையை பரப்புங்கள்",
        
        "ai_donor_matching" to " தானியங்கி பொருத்தம்",
        "scanning_donors" to " %d கொடையாளர்களை ஸ்கேன் செய்கிறது",
        "all_donors" to "அனைத்து கொடையாளர்கள்",
        "available" to "கிடைக்கக்கூடியது",
        "busy" to "பிஸியாக உள்ளது",
        "within_5km" to "5 கி.மீ க்குள்",
        "exact_match" to "சரியான",
        "compatible_match" to "இணக்கமான",
        "call_donor" to "அழைக்கவும்",
        "chat_donor" to "அரட்டையடிக்கவும்",
        
        "remember_me" to "என்னை நினைவில் கொள்",
        "error_invalid_credentials" to "தவறான தொலைபேசி எண் அல்லது கடவுச்சொல். சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
        "error_network_unavailable" to "பிணையம் கிடைக்கவில்லை. உங்கள் இணைப்பைச் சரிபார்க்கவும்.",
        "error_server_error" to "சேவையக பிழை. பின்னர் மீண்டும் முயற்சிக்கவும்.",
        "error_not_found" to "சேவையகம் கிடைக்கவில்லை.",
        "error_invalid_password" to "தவறான கடவுச்சொல். கடவுச்சொல்லைச் சரிபார்த்து மீண்டும் முயலவும்.",
        "error_not_registered" to "இந்த தொலைபேசி எண் அல்லது மின்னஞ்சல் பதிவு செய்யப்படவில்லை.",
        "please_fill_all_fields_pwd" to "அனைத்து புலங்களையும் நிரப்பவும். கடவுச்சொல் குறைந்தது 6 எழுத்துகளாக இருக்க வேண்டும்.",
        "please_enter_age_gender" to "உங்கள் வயது மற்றும் பாலினத்தை உள்ளிடவும்.",
        "you_are_here" to "நீங்கள் இங்கே இருக்கிறீர்கள்",
        "please_enter_phone" to "தொலைபேசி எண்ணை உள்ளிடவும்",
        "reset_otp_sent" to "மீட்டமைப்பு OTP அனுப்பப்பட்டது: 654321",
        "please_fill_all_fields" to "அனைத்து புலங்களையும் நிரப்பவும்",
        "password_reset_success" to "கடவுச்சொல் வெற்றிகரமாக மீட்டமைக்கப்பட்டது! தயவுசெய்து உள்நுழையவும்.",
        
        "recent_alerts" to "அறிவிப்புகள்",
        "no_recent_alerts" to "அண்மை எச்சரிக்கைகள் எதுவுமில்லை",
        "create_account" to "கணக்கை உருவாக்கு",
        "new_here" to "புதியவரா? ",
        "register" to "பதிவு செய்யவும்",
        "full_name" to "முழு பெயர்",
        "confirm_password" to "கடவுச்சொல்லை உறுதிப்படுத்து",
        "user_type" to "பயனர் வகை",
        "donor" to "கொடையாளர்",
        "patient" to "நோயாளி",
        "hospital" to "மருத்துவமனை",
        "license_number" to "உரிம எண்",
        "already_member" to "ஏற்கனவே உறுப்பினரா? ",
        "otp_title" to "OTP சரிபார்ப்பு",
        "otp_desc" to "உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6 இலக்க OTP குறியீட்டை உள்ளிடவும்.",
        "verify" to "சரிபார்க்கவும்",
        "resend_otp" to "OTP ஐ மீண்டும் அனுப்பு",
        
        "location" to "இருப்பிடம்",
        "update_location" to "இருப்பிடத்தை புதுப்பிக்கவும்",
        "select_state" to "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
        "select_district" to "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
        "enter_city" to "நகரத்தை உள்ளிடவும்",
        "save" to "சேமி",
        "cancel" to "ரத்துசெய்",
        "accept" to "ஏற்கவும்",
        "decline" to "நிராகரிக்கவும்",
        "today_status" to "இன்றைய நிலை",
        "available_hours" to "கிடைக்கும் நேரம்",
        "morning" to "காலை",
        "afternoon" to "மதியம்",
        "evening" to "மாலை",
        "sos_broadcast_success" to "அவசர SOS வெற்றிகரமாக இன்-ஆப்பில் ஒளிபரப்பப்பட்டது!",
        "sos_request_desc" to "இரத்தம் தேவையா? பொருந்தக்கூடிய கொடையாளர்களுக்குத் தெரிவிக்க தட்டவும்",
        "best_match" to "உங்களுக்கு சிறந்த பொருத்தம்",
        "see_all" to "அனைத்தையும் பார் >",
        "contact_donor" to "கொடையாளரைத் தொடர்பு கொள்ளவும்",
        "other_compatible" to "பிற இணக்கமான கொடையாளர்கள்",
        "view_all" to "அனைத்தையும் காண்க >",
        "no_donors_found" to "அருகிலுள்ள பிற கொடையாளர்கள் யாரும் காணப்படவில்லை",
        "update_avail_today" to "இன்று உங்கள் இருப்பை புதுப்பிக்கவா?",
        "let_patients_know" to "நீங்கள் இரத்தம் கொடுக்க தயாராக இருக்கிறீர்களா என்பதை நோயாளிகளுக்கு தெரியப்படுத்துங்கள்.",
        "update" to "புதுப்பிக்கவும்",
        "donor_summary" to "உங்கள் கொடையாளர் சுருக்கம்",
        "donor_registered" to "❤️ நீங்கள் இரத்தக் கொடையாளராகப் பதிவு செய்யப்பட்டுள்ளீர்கள்!",
        "donor_registered_desc" to "அருகிலுள்ள நோயாளிகளுக்கு உங்கள் இரத்த வகை தேவைப்படும்போது, ​​அவர்கள் உங்கள் சுயவிவரத்தைப் பார்த்து உங்களைத் தொடர்பு கொள்ளலாம்.",
        "available_now" to "இப்போது கிடைக்கிறது",
        "day_lock_rule" to "90-நாட்கள் பூட்டு விதி",
        "alerts_active" to "அலர்ட்கள் செயலில் உள்ளன",
        "ai_tip_of_day" to "இன்றைய  உதவிக்குறிப்பு",
        "error_already_registered" to "இந்த தொலைபேசி எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. தயவுசெய்து உள்நுழையவும்.",
        "save_login_title" to "உள்நுழைவு தகவலைச் சேமிக்கவா?",
        "save_login_desc" to "அடுத்த முறை வேகமாக உள்நுழைய உங்கள் தகவலைச் சேமிக்கவும்.",
        "not_now" to "இப்போது இல்லை",
        "onboarding_title_1" to " தானியங்கி பொருத்தம்",
        "onboarding_desc_1" to "எங்கள்  சில நொடிகளில் அருகிலுள்ள மிகவும் இணக்கமான இரத்தக் கொடையாளரைக் கண்டறியும் - இரத்தக் குழு, சுகாதார மதிப்பெண் மற்றும் தூரம் ஆகியவற்றால் பொருத்தப்படும்.",
        "onboarding_title_2" to "அவசரகால SOS எச்சரிக்கைகள்",
        "onboarding_desc_2" to "ஆப் அறிவிப்புகள் மற்றும் எஸ்எம்எஸ் மூலம் ஒரே நேரத்தில் SOS எச்சரிக்கைகளை அனுப்பவும். இணையம் இல்லாவிட்டாலும் வேலை செய்யும்.",
        "onboarding_title_3" to "நேரடி கொடையாளர் கண்காணிப்பு",
        "onboarding_desc_3" to "அருகிலுள்ள கொடையாளர்களின் நேரடி வரைபடத்தைக் காண்க, அவற்றின் தற்போதைய நிலை மற்றும் உடனடி புதுப்பிப்புகளுடன்.",
        "skip" to "தவிர்",
        "get_started" to "தொடங்குவோம்",
        "forgot_password" to "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
        "please_enter_phone_password" to "உங்கள் தொலைபேசி எண் மற்றும் கடவுச்சொல்லை உள்ளிடவும்",
        "reset_password_title" to "கடவுச்சொல்லை மீட்டமை",
        "forgot_password_desc" to "உருவகப்படுத்தப்பட்ட மீட்டமைப்பு OTP (654321) ஐப் பெற உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்.",
        "phone_number_placeholder" to "தொலைபேசி எண்",
        "send_otp" to "OTP அனுப்பு",
        "cancel" to "ரத்து செய்",
        "enter_new_password_title" to "புதிய கடவுச்சொல்லை உள்ளிடவும்",
        "enter_new_password_desc" to "உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட OTP குறியீட்டை உள்ளிட்டு புதிய கடவுச்சொல்லைத் தேர்ந்தெடுக்கவும்.",
        "otp_code_placeholder" to "OTP குறியீடு (உதாரணமாக 654321)",
        "new_password_placeholder" to "புதிய கடவுச்சொல்",
        "create_account_title" to "கணக்கை உருவாக்கு",
        "i_am_a" to "நான் ஒரு...",
        "choose_role_desc" to "தொடங்குவதற்கு உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்",
        "blood_donor_role" to "இரத்தக் கொடையாளர்",
        "blood_donor_role_desc" to "கொடையாளராகப் பதிவுசெய்து உயிர்களைக் காக்க உதவுங்கள்.",
        "patient_family_role" to "நோயாளி / குடும்பம்",
        "patient_family_role_desc" to "இரத்தம் அவசரமாகக் கோரவும்.",
        "hospital_role" to "மருத்துவமனை",
        "hospital_role_desc" to "இரத்தக் கோரிக்கைகளை நிர்வகிக்கவும்.",
        "basic_info_title" to "அடிப்படைத் தகவல்",
        "institution_name_label" to "நிறுவனத்தின் பெயர்",
        "patient_family_name_label" to "நோயாளி / குடும்பப் பெயர்",
        "full_name_label" to "முழு பெயர்",
        "email_address_label" to "மின்னஞ்சல் முகவரி",
        "continue_button" to "தொடரவும்",
        "patient_details_title" to "நோயாளி விவரங்கள்",
        "donor_details_title" to "கொடையாளர் விவரங்கள்",
        "last_donation_date_label" to "கடைசி கொடை தேதி (YYYY-MM-DD) [விருப்பத்திற்குரியது]",
        "save_button" to "சேமி",
        "verify_phone_title" to "தொலைபேசியைச் சரிபார்க்கவும்",
        "enter_otp_code_title" to "OTP குறியீட்டை உள்ளிடவும்",
        "otp_sent_desc" to "நாங்கள் %s க்கு சரிபார்ப்புக் குறியீட்டை அனுப்பியுள்ளோம்.\nஉங்கள் கணக்கைச் செயல்படுத்த கீழே உள்ள குறியீட்டை உள்ளிடவும்.",
        "enter_6digit_placeholder" to "6 இலக்க குறியீட்டை உள்ளிடவும்",
        "simulated_otp_banner" to "உருவகப்படுத்தப்பட்ட OTP குறியீடு 123456 ஆகும்",
        "verify_activate_button" to "சரிபார்த்து செயல்படுத்துக",
        "please_enter_valid_otp" to "முறையான 6 இலக்க குறியீட்டை உள்ளிடவும்",
        "compatible_percent" to "%s%% இணக்கமானது",
        "km_away" to "%s கிமீ தொலைவில்",
        "messages_title" to "செய்திகள்",
        "no_recent_conversations" to "சமீபத்திய உரையாடல்கள் எதுவும் இல்லை",
        "notifications_title" to "அறிவிப்புகள்",
        "mark_all_read" to "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
        "no_recent_alerts" to "சமீபத்திய எச்சரிக்கைகள் எதுவும் இல்லை.",
        "alert_needed_template" to "%s: %s இல் %d அலகு %s தேவைப்படுகிறது",
        "my_profile_title" to "எனது சுயவிவரம்",
        "complete_profile_title" to "உங்கள் சுயவிவரத்தை முழுமையாக்குங்கள்",
        "complete_profile_desc" to "தொடர உங்கள் இரத்த வகை மற்றும் விவரங்களை உள்ளிடவும்.",
        "save_continue_button" to "சேமித்து தொடரவும்",
        "ready_to_donate" to "இப்போது தானம் செய்யத் தயார்",
        "currently_unavailable" to "தற்போது கிடைக்கவில்லை",
        "not_available_to_donate" to "தானம் செய்யக் கிடைக்கவில்லை",
        "morning_hours" to "முற்பகல் 6:00 - பிற்பகல் 12:00",
        "afternoon_hours" to "பிற்பகல் 12:00 - மாலை 6:00",
        "evening_hours" to "மாலை 6:00 - இரவு 10:00",
        "updated_just_now" to "இப்போது புதுப்பிக்கப்பட்டது",
        "updated_minutes_ago" to "%d நிமிடங்களுக்கு முன்பு புதுப்பிக்கப்பட்டது",
        "preferences_header" to "விருப்பத்தேர்வுகள்",
        "server_url_label" to "சேவையக URL",
        "server_url_desc" to "சேவையக இணைப்பை உள்ளமைக்கவும்",
        "server_config_title" to "சேவையக கட்டமைப்பு",
        "enter_server_url_desc" to "சேவையக API URL ஐ உள்ளிடவும்:",
        "ok_button" to "சரி",
        "critical_sos_alerts_channel" to "அவசரகால SOS எச்சரிக்கைகள்",
        "critical_sos_desc" to "உடனடி உயிர் காக்கும் இரத்த தேவைகள்",
        "standard_sos_alerts_channel" to "சாதாரண SOS எச்சரிக்கைகள்",
        "standard_sos_desc" to "பொதுவான இரத்த தேவைகள்",
        "urgent_blood_needed" to "🚨 அவசரம்: %s தேவைப்படுகிறது!",
        "blood_request_title" to "இரத்தக் கோரிக்கை: %s",
        "units_needed_at_hospital" to "%s இல் %d அலகுகள் தேவைப்படுகிறது."
    )

    private val hi = mapOf(
        "settings" to "सेटिंग्स",
        "account" to "खाता",
        "edit_profile" to "प्रोफ़ाइल संपादित करें",
        "change_password" to "पासवर्ड बदलें",
        "push_notifications" to "अधिसूचनाएं",
        "sos_alerts" to "एसओएस अलर्ट",
        "privacy_policy" to "गोपनीयता नीति",
        "about" to "स्मार्ट ब्लड फाइंडर के बारे में",
        "logout" to "लॉगआउट",
        "select_language" to "पसंदीदा भाषा",
        "english" to "अंग्रेजी (English)",
        "tamil" to "तमिल (தமிழ்)",
        "hindi" to "हिंदी (हिन्दी)",
        "save_changes" to "बदलाव सहेजें",
        "welcome" to "स्वागत हे",
        "sign_in_save_lives" to "जीवन बचाने के लिए साइन इन करें",
        "email_or_phone" to "ईमेल या फोन नंबर",
        "password" to "पासवर्ड",
        "login" to "लॉगिन",
        "language" to "भाषा",
        "change_language_desc" to "डिफ़ॉल्ट एप्लिकेशन भाषा चुनें",
        "theme" to "थीम सेटिंग्स",
        "edit_profile_desc" to "अपना नाम, आयु, रक्त समूह अपडेट करें",
        "change_password_desc" to "अपने खाते को सुरक्षित रखें",
        "notifications_desc" to "रक्त अनुरोधों के बारे में सूचित रहें",
        "sos_desc" to "पास में आपातकालीन रक्त अलर्ट प्राप्त करें",
        "privacy_desc" to "हम आपके डेटा को कैसे प्रबंधित करते हैं",
        "about_desc" to "संस्करण 1.0.0",
        
        "home" to "होम",
        "map" to "मानचित्र",
        "chat" to "चैट",
        "alerts" to "अलर्ट",
        "profile" to "प्रोफ़ाइल",
        
        "hospital_dashboard" to "अस्पताल डैशबोर्ड",
        "donor_dashboard" to "दाता डैशबोर्ड",
        "patient_dashboard" to "रोगी डैशबोर्ड",
        "good_morning" to "शुभ प्रभात 👋",
        "blood_group" to "रक्त समूह",
        "age" to "आयु",
        "gender" to "लिंग",
        "last_donated" to "पिछली बार दान किया",
        "next_eligible" to "अगला योग्य",
        "phone" to "फ़ोन",
        "email" to "ईमेल",
        
        "emergency_sos" to "आपातकालीन एसओएस",
        "request_blood" to "रक्त का अनुरोध करें",
        "blood_group_needed" to "रक्त समूह की आवश्यकता",
        "hospital_name" to "अस्पताल का नाम",
        "units_required" to "आवश्यक इकाइयां",
        "urgency" to "अति आवश्यकता",
        "submit_request" to "अनुरोध जमा करें",
        "create_blood_request" to "रक्त अनुरोध बनाएं",
        "hospital_name_location" to "अस्पताल का नाम / स्थान",
        "units_pints" to "इकाइयां (पिंट्स)",
        "urgency_level" to "अति आवश्यकता (कम/उच्च/गंभीर)",
        "broadcast_request" to "दाताओं को अनुरोध प्रसारित करें",
        
        "ai_donor_matching" to "एआई दाता मिलान",
        "scanning_donors" to "एआई %d दाताओं को स्कैन कर रहा है",
        "all_donors" to "सभी दाता",
        "available" to "उपलब्ध",
        "busy" to "व्यस्त",
        "within_5km" to "5 किमी के भीतर",
        "exact_match" to "सटीक",
        "compatible_match" to "संगत",
        "call_donor" to "कॉल करें",
        "chat_donor" to "चैट करें",
        
        "remember_me" to "मुझे याद रखें",
        "error_invalid_credentials" to "गलत फ़ोन नंबर या पासवर्ड। कृपया अपनी साख जांचें और पुन: प्रयास करें।",
        "error_network_unavailable" to "नेटवर्क अनुपलब्ध। कृपया अपना कनेक्शन जांचें।",
        "error_server_error" to "सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।",
        "error_not_found" to "सर्वर नहीं मिला।",
        "error_invalid_password" to "गलत पासवर्ड। कृपया अपना पासवर्ड जांचें और पुन: प्रयास करें।",
        "error_not_registered" to "यह फ़ोन नंबर या ईमेल पंजीकृत नहीं है।",
        "please_fill_all_fields_pwd" to "कृपया सभी फ़ील्ड भरें। पासवर्ड कम से कम 6 वर्णों का होना चाहिए।",
        "please_enter_age_gender" to "कृपया अपनी आयु और लिंग दर्ज करें।",
        "you_are_here" to "आप यहाँ हैं",
        "please_enter_phone" to "कृपया फोन नंबर दर्ज करें",
        "reset_otp_sent" to "रीसेट ओटीपी भेजा गया: 654321",
        "please_fill_all_fields" to "कृपया सभी क्षेत्र भरें",
        "password_reset_success" to "पासवर्ड सफलतापूर्वक रीसेट हो गया! कृपया लॉगिन करें।",
        
        "recent_alerts" to "अधिसूचनाएं",
        "no_recent_alerts" to "कोई हालिया अलर्ट नहीं",
        "create_account" to "खाता बनाएं",
        "new_here" to "यहाँ नए हैं? ",
        "register" to "पंजीकरण",
        "full_name" to "पूरा नाम",
        "confirm_password" to "पासवर्ड की पुष्टि करें",
        "user_type" to "उपयोगकर्ता प्रकार",
        "donor" to "दाता",
        "patient" to "रोगी",
        "hospital" to "अस्पताल",
        "license_number" to "लाइसेंस संख्या",
        "already_member" to "पहले से ही सदस्य हैं? ",
        "otp_title" to "ओटीपी सत्यापन",
        "otp_desc" to "आपके फोन पर भेजा गया 6-अंकीय ओटीपी कोड दर्ज करें।",
        "verify" to "सत्यापित करें",
        "resend_otp" to "ओटीपी पुनः भेजें",
        
        "location" to "स्थान",
        "update_location" to "स्थान अपडेट करें",
        "select_state" to "राज्य चुनें",
        "select_district" to "जिला चुनें",
        "enter_city" to "शहर दर्ज करें",
        "save" to "सहेजें",
        "cancel" to "रद्द करें",
        "accept" to "स्वीकार करें",
        "decline" to "अस्वीकार करें",
        "today_status" to "आज की स्थिति",
        "available_hours" to "उपलब्ध घंटे",
        "morning" to "सुबह",
        "afternoon" to "दोपहर",
        "evening" to "शाम",
        "sos_broadcast_success" to "आपातकालीन एसओएस सफलतापूर्वक इन-ऐप प्रसारित किया गया!",
        "sos_request_desc" to "रक्त की आवश्यकता है? मेल खाने वाले दाताओं को सचेत करने के लिए टैप करें",
        "best_match" to "आपके लिए सबसे अच्छा मिलान",
        "see_all" to "सभी देखें >",
        "contact_donor" to "दाता से संपर्क करें",
        "other_compatible" to "अन्य संगत दाता",
        "view_all" to "सभी देखें >",
        "no_donors_found" to "आस-पास कोई अन्य दाता नहीं मिला",
        "update_avail_today" to "आज अपनी उपलब्धता अपडेट करें?",
        "let_patients_know" to "रोगियों को बताएं कि क्या आप दान करने के लिए तैयार हैं।",
        "update" to "अपडेट करें",
        "donor_summary" to "आपका दाता सारांश",
        "donor_registered" to "❤️ आप रक्त दाता के रूप में पंजीकृत हैं!",
        "donor_registered_desc" to "जब आपके आस-पास के रोगियों को आपके रक्त समूह की आवश्यकता होगी, तो वे आपकी प्रोफ़ाइल देख सकेंगे और आपसे संपर्क कर सकेंगे।",
        "available_now" to "अभी उपलब्ध है",
        "day_lock_rule" to "90-दिन का लॉक नियम",
        "alerts_active" to "अलर्ट सक्रिय हैं",
        "ai_tip_of_day" to "दिन का एआई सुझाव",
        "error_already_registered" to "यह फ़ोन नंबर पहले से पंजीकृत है। कृपया लॉगिन करें।",
        "save_login_title" to "लॉगिन जानकारी सहेजें?",
        "save_login_desc" to "अगली बार तेज़ी से लॉगिन करने के लिए अपनी जानकारी सहेजें।",
        "not_now" to "अभी नहीं",
        "onboarding_title_1" to "एआई दाता मिलान",
        "onboarding_desc_1" to "हमारा एआई सेकंडों में पास के सबसे अनुकूल रक्तदाता को ढूंढता है - रक्त समूह, स्वास्थ्य स्कोर और दूरी द्वारा मिलान किया जाता है।",
        "onboarding_title_2" to "आपातकालीन एसओएस अलर्ट",
        "onboarding_desc_2" to "ऐप नोटिफिकेशन और एसएमएस के जरिए एक साथ एसओएस अलर्ट भेजें। बिना इंटरनेट के भी काम करता है।",
        "onboarding_title_3" to "लाइव दाता ट्रैकिंग",
        "onboarding_desc_3" to "स्थिति और वास्तविक समय अपडेट के साथ अपने पास उपलब्ध दाताओं का लाइव मानचित्र देखें।",
        "skip" to "छोड़ें",
        "get_started" to "शुरू करें",
        "forgot_password" to "पासवर्ड भूल गए?",
        "please_enter_phone_password" to "कृपया अपना फ़ोन नंबर और पासवर्ड दर्ज करें",
        "reset_password_title" to "पासवर्ड रीसेट करें",
        "forgot_password_desc" to "सिम्युलेटेड रीसेट ओटीपी (654321) प्राप्त करने के लिए अपना फोन नंबर दर्ज करें।",
        "phone_number_placeholder" to "फ़ोन नंबर",
        "send_otp" to "ओटीपी भेजें",
        "cancel" to "रद्द करें",
        "enter_new_password_title" to "नया पासवर्ड दर्ज करें",
        "enter_new_password_desc" to "अपने फोन पर भेजे गए ओटीपी कोड को दर्ज करें और एक नया पासवर्ड चुनें।",
        "otp_code_placeholder" to "ओटीपी कोड (उदा. 654321)",
        "new_password_placeholder" to "नया पासवर्ड",
        "create_account_title" to "खाता बनाएं",
        "i_am_a" to "मैं एक...",
        "choose_role_desc" to "शुरू करने के लिए अपनी भूमिका चुनें",
        "blood_donor_role" to "रक्त दाता",
        "blood_donor_role_desc" to "दाता के रूप में पंजीकरण करें और जीवन बचाने में मदद करें।",
        "patient_family_role" to "रोगी / परिवार",
        "patient_family_role_desc" to "रक्त का तत्काल अनुरोध करें।",
        "hospital_role" to "अस्पताल",
        "hospital_role_desc" to "रक्त अनुरोधों का प्रबंधन करें।",
        "basic_info_title" to "बुनियादी जानकारी",
        "institution_name_label" to "संस्थान का नाम",
        "patient_family_name_label" to "रोगी / परिवार का नाम",
        "full_name_label" to "पूरा नाम",
        "email_address_label" to "ईमेल पता",
        "continue_button" to "जारी रखें",
        "patient_details_title" to "रोगी का विवरण",
        "donor_details_title" to "दाता विवरण",
        "last_donation_date_label" to "अंतिम दान तिथि (YYYY-MM-DD) [वैकल्पिक]",
        "save_button" to "सहेजें",
        "verify_phone_title" to "फोन सत्यापित करें",
        "enter_otp_code_title" to "ओटीपी कोड दर्ज करें",
        "otp_sent_desc" to "हमने %s पर एक सत्यापन कोड भेजा है।\nअपने खाते को सक्रिय करने के लिए कृपया नीचे कोड दर्ज करें।",
        "enter_6digit_placeholder" to "6-अंकीय कोड दर्ज करें",
        "simulated_otp_banner" to "सिम्युलेटेड ओटीपी कोड 123456 है",
        "verify_activate_button" to "सत्यापित करें और सक्रिय करें",
        "please_enter_valid_otp" to "कृपया एक वैध 6-अंकीय कोड दर्ज करें",
        "compatible_percent" to "%s%% संगत",
        "km_away" to "%s किमी दूर",
        "messages_title" to "संदेश",
        "no_recent_conversations" to "कोई हालिया बातचीत नहीं",
        "notifications_title" to "अधिसूचनाएं",
        "mark_all_read" to "सभी को पढ़ा हुआ चिह्नित करें",
        "no_recent_alerts" to "कोई हालिया अलर्ट नहीं।",
        "alert_needed_template" to "%s: %s पर %d यूनिट %s की आवश्यकता है",
        "my_profile_title" to "मेरी प्रोफ़ाइल",
        "complete_profile_title" to "अपनी प्रोफ़ाइल पूरी करें",
        "complete_profile_desc" to "जारी रखने के लिए कृपया अपना रक्त समूह और विवरण दर्ज करें।",
        "save_continue_button" to "सहेजें और जारी रखें",
        "ready_to_donate" to "अब दान करने के लिए तैयार",
        "currently_unavailable" to "वर्तमान में अनुपलब्ध",
        "not_available_to_donate" to "दान करने के लिए उपलब्ध नहीं",
        "morning_hours" to "सुबह 6:00 - दोपहर 12:00",
        "afternoon_hours" to "दोपहर 12:00 - शाम 6:00",
        "evening_hours" to "शाम 6:00 - रात 10:00",
        "updated_just_now" to "अभी-अभी अपडेट किया गया",
        "updated_minutes_ago" to "%d मिनट पहले अपडेट किया गया",
        "preferences_header" to "प्राथमिकताएं",
        "server_url_label" to "सर्वर URL",
        "server_url_desc" to "बैकएंड कनेक्शन कॉन्फ़िगर करें",
        "server_config_title" to "सर्वर कॉन्फ़िगरेशन",
        "enter_server_url_desc" to "बैकएंड एपीआई सर्वर यूआरएल दर्ज करें:",
        "ok_button" to "ठीक है",
        "critical_sos_alerts_channel" to "गंभीर एसओएस अलर्ट",
        "critical_sos_desc" to "तत्काल जीवन रक्षक रक्त आवश्यकताएं",
        "standard_sos_alerts_channel" to "सामान्य एसओएस अलर्ट",
        "standard_sos_desc" to "सामान्य रक्त आवश्यकताएं",
        "urgent_blood_needed" to "🚨 तत्काल: %s की आवश्यकता है!",
        "blood_request_title" to "रक्त अनुरोध: %s",
        "units_needed_at_hospital" to "%s पर %d इकाइयों की आवश्यकता है।"
    )

    fun get(key: String, lang: String): String {
        val dict = when(lang.lowercase()) {
            "ta" -> ta
            "hi" -> hi
            else -> en
        }
        return dict[key] ?: en[key] ?: key
    }
}
